// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-PpfK3ry9Y2oNVBXs6SI37F2pAU5efZc',
    appId: '1:473415287643:web:aa025d1a9d740fba48107e',
    messagingSenderId: '473415287643',
    projectId: 'madassignment-db8ad',
    authDomain: 'madassignment-db8ad.firebaseapp.com',
    storageBucket: 'madassignment-db8ad.appspot.com',
    measurementId: 'G-S5P4K74ZEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkScqPNy6JjHfx3uXVW9PLtcAu7wi-kJo',
    appId: '1:473415287643:android:f811a007df8b4b4248107e',
    messagingSenderId: '473415287643',
    projectId: 'madassignment-db8ad',
    storageBucket: 'madassignment-db8ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv-exMeSin0ZvDLAajB2LVOAATcF2K9yU',
    appId: '1:473415287643:ios:1f45c8e4ef9700b748107e',
    messagingSenderId: '473415287643',
    projectId: 'madassignment-db8ad',
    storageBucket: 'madassignment-db8ad.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv-exMeSin0ZvDLAajB2LVOAATcF2K9yU',
    appId: '1:473415287643:ios:1f45c8e4ef9700b748107e',
    messagingSenderId: '473415287643',
    projectId: 'madassignment-db8ad',
    storageBucket: 'madassignment-db8ad.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-PpfK3ry9Y2oNVBXs6SI37F2pAU5efZc',
    appId: '1:473415287643:web:342643a1bc2f88d748107e',
    messagingSenderId: '473415287643',
    projectId: 'madassignment-db8ad',
    authDomain: 'madassignment-db8ad.firebaseapp.com',
    storageBucket: 'madassignment-db8ad.appspot.com',
    measurementId: 'G-VK7SYY2CVE',
  );
}
